#!/usr/bin/env bash
set -euo pipefail
OUTLIER_CSV="./tmp/outlier_global.csv"
CLUSTER_CSV="./tmp/clustering_global.csv"
OUTPUT="./benchmark-data.js"
CLUSTBENCH_2D_CSV="./tmp/clustbench/pairwise_wins_2D_ari.csv"
CLUSTBENCH_MULTID_CSV="./tmp/clustbench/pairwise_wins_multiD_ari.csv"
CLUSTBENCH_METADATA="./tmp/clustbench/pairwise_wins_ari.metadata.json"

python3 - "$OUTLIER_CSV" "$CLUSTER_CSV" "$CLUSTBENCH_2D_CSV" "$CLUSTBENCH_MULTID_CSV" "$CLUSTBENCH_METADATA" "$OUTPUT" << 'PYEOF'
import csv, json, sys, math

outlier_csv, cluster_csv, pairwise_2d_csv, pairwise_multid_csv, pairwise_metadata, output = sys.argv[1:]

def to_float(v):
    try:
        f = float(v)
        return None if math.isnan(f) else f
    except (ValueError, TypeError):
        return None

def to_int(v):
    try:
        f = float(v)
        return None if math.isnan(f) else int(f)
    except (ValueError, TypeError):
        return None

def parse_outlier(path):
    data = {}
    with open(path) as f:
        reader = csv.DictReader(f)
        for row in reader:
            ds = row['dataset']
            algo = row['algorithm']
            if ds not in data:
                data[ds] = {}
            data[ds][algo] = {
                'status': row['status'],
                'n_samples': to_int(row.get('n_samples')),
                'n_features': to_int(row.get('n_features')),
                'auc': to_float(row.get('auc')),
                'f1': to_float(row.get('f1')),
                'ari': to_float(row.get('ari')),
                'ami': to_float(row.get('ami')),
                'precision': to_float(row.get('precision')),
                'recall': to_float(row.get('recall')),
                'time_seconds': to_float(row.get('time_seconds')),
            }
    return data

def parse_cluster(path):
    data = {}
    with open(path) as f:
        reader = csv.DictReader(f)
        for row in reader:
            ds = row['dataset']
            algo = row['algorithm']
            if ds not in data:
                data[ds] = {}
            data[ds][algo] = {
                'status': row['status'],
                'n_samples': to_int(row.get('n_samples')),
                'n_features': to_int(row.get('n_features')),
                'true_k': to_int(row.get('true_k')),
                'ari': to_float(row.get('ari')),
                'ami': to_float(row.get('ami')),
                'nmi': to_float(row.get('nmi')),
                'silhouette': to_float(row.get('silhouette')),
                'n_pred_clusters': to_int(row.get('n_pred_clusters')),
                'time_seconds': to_float(row.get('time_seconds')),
            }
    return data

def parse_pairwise(path, dimension, metadata):
    with open(path) as f:
        reader = csv.DictReader(f)
        algorithms = [name for name in reader.fieldnames if name != 'row_wins_over_column']
        wins = {}
        for row in reader:
            wins[row['row_wins_over_column']] = {
                algo: to_int(row.get(algo)) for algo in algorithms
            }
    counts = metadata.get('groups', {}).get(dimension, {}).get('dataset_count_by_algorithm', {})
    comparable = min(counts.values()) if counts else None
    return {'algorithms': algorithms, 'wins': wins, 'comparable_datasets': comparable}

outlier = parse_outlier(outlier_csv)
cluster = parse_cluster(cluster_csv)
with open(pairwise_metadata) as f:
    clustbench_meta = json.load(f)
clustbench = {
    '2D': parse_pairwise(pairwise_2d_csv, '2D', clustbench_meta),
    'multiD': parse_pairwise(pairwise_multid_csv, 'multiD', clustbench_meta),
}

with open(output, 'w') as f:
    f.write('// Auto-generated by build_data.sh — do not edit manually\n')
    f.write('var OUTLIER_DATA = ')
    f.write(json.dumps(outlier, indent=2))
    f.write(';\n')
    f.write('var CLUSTER_DATA = ')
    f.write(json.dumps(cluster, indent=2))
    f.write(';\n')
    f.write('var CLUSTBENCH_PAIRWISE = ')
    f.write(json.dumps(clustbench, indent=2))
    f.write(';\n')

print(f"Generated {output} with {len(outlier)} outlier datasets and {len(cluster)} cluster datasets.")
PYEOF
