#!/usr/bin/env bash
set -euo pipefail
OUTLIER_CSV="./tmp/outlier_global.csv"
CLUSTER_CSV="./tmp/clustering_global.csv"
OUTPUT="./benchmark-data.js"
CLUSTBENCH_2D_CSV="./tmp/clustbench/deltric_vs_baselines_2D_ari.csv"
CLUSTBENCH_MULTID_CSV="./tmp/clustbench/deltric_vs_baselines_multiD_ari.csv"

python3 - "$OUTLIER_CSV" "$CLUSTER_CSV" "$CLUSTBENCH_2D_CSV" "$CLUSTBENCH_MULTID_CSV" "$OUTPUT" << 'PYEOF'
import csv, json, sys, math

outlier_csv, cluster_csv, deltric_2d_csv, deltric_multid_csv, output = sys.argv[1:]

def to_float(v):
    try:
        f = float(v)
        return None if math.isnan(f) else f
    except (ValueError, TypeError):
        return None

def to_int(v):
    try:
        f = float(v)
        return None if math.isnan(f) else int(f)
    except (ValueError, TypeError):
        return None

def parse_outlier(path):
    data = {}
    with open(path) as f:
        reader = csv.DictReader(f)
        for row in reader:
            ds = row['dataset']
            algo = row['algorithm']
            if ds not in data:
                data[ds] = {}
            data[ds][algo] = {
                'status': row['status'],
                'n_samples': to_int(row.get('n_samples')),
                'n_features': to_int(row.get('n_features')),
                'auc': to_float(row.get('auc')),
                'f1': to_float(row.get('f1')),
                'ari': to_float(row.get('ari')),
                'ami': to_float(row.get('ami')),
                'precision': to_float(row.get('precision')),
                'recall': to_float(row.get('recall')),
                'time_seconds': to_float(row.get('time_seconds')),
            }
    return data

def parse_cluster(path):
    data = {}
    with open(path) as f:
        reader = csv.DictReader(f)
        for row in reader:
            ds = row['dataset']
            algo = row['algorithm']
            if ds not in data:
                data[ds] = {}
            data[ds][algo] = {
                'status': row['status'],
                'n_samples': to_int(row.get('n_samples')),
                'n_features': to_int(row.get('n_features')),
                'true_k': to_int(row.get('true_k')),
                'ari': to_float(row.get('ari')),
                'ami': to_float(row.get('ami')),
                'nmi': to_float(row.get('nmi')),
                'silhouette': to_float(row.get('silhouette')),
                'n_pred_clusters': to_int(row.get('n_pred_clusters')),
                'time_seconds': to_float(row.get('time_seconds')),
            }
    return data

def parse_deltric_comparison(path):
    with open(path) as f:
        rows = []
        for row in csv.DictReader(f):
            rows.append({
                'comparator': row['comparator'],
                'deltric_mean': to_float(row['deltric_mean']),
                'comparator_mean': to_float(row['comparator_mean']),
                'mean_delta': to_float(row['mean_delta']),
                'deltric_wins': to_int(row['deltric_wins']),
                'deltric_losses': to_int(row['deltric_losses']),
                'ties': to_int(row['ties']),
                'comparable_datasets': to_int(row['comparable_datasets']),
            })
    return rows

outlier = parse_outlier(outlier_csv)
cluster = parse_cluster(cluster_csv)
clustbench = {
    '2D': parse_deltric_comparison(deltric_2d_csv),
    'multiD': parse_deltric_comparison(deltric_multid_csv),
}

with open(output, 'w') as f:
    f.write('// Auto-generated by build_data.sh — do not edit manually\n')
    f.write('var OUTLIER_DATA = ')
    f.write(json.dumps(outlier, indent=2))
    f.write(';\n')
    f.write('var CLUSTER_DATA = ')
    f.write(json.dumps(cluster, indent=2))
    f.write(';\n')
    f.write('var CLUSTBENCH_DELTRIC_COMPARISON = ')
    f.write(json.dumps(clustbench, indent=2))
    f.write(';\n')

print(f"Generated {output} with {len(outlier)} outlier datasets and {len(cluster)} cluster datasets.")
PYEOF
